### ISSUE TITLE
[Feat Request] Add a rule for Dynabot

### ISSUE THREAD

**Issue by ninoseki** [ninoseki/abuse_whois#8]
[Dynabot](https://www.dynadot.com/) has a web form to report abuse.

- https://www.dynadot.com/report_abuse.html

```yaml
contact:
  provider: Dynabot
  address: https://www.dynadot.com/report_abuse.html
keywords:
  - abuse@dynadot.com
```
